## Copyright (C)2020-2026 by John A Kline (john@johnkline.com)
## Distributed under the terms of the GNU Public License (GPLv3)
## See LICENSE for your rights.

#errorCatcher Echo

    <div id='identifier_widget' class="widget">
      <div class="widget_title">
      </div>
      <div class="widget_contents">
        <div class="footnote">
          <table class="footer-indoor">
            <tr>
              <td class="footer-gap-1"></td>
              <td id="indoor_co2"></td>
              <td class="footer-gap-2"></td>
              <td id="indoor_aqi"></td>
              <td class="footer-gap-2"></td>
              <td id="aqi"></td>
              <td class="footer-gap-2"></td>
              <td id="activity-string"></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
