## Copyright (C)2020-2025 by John A Kline (john@johnkline.com)
## Distributed under the terms of the GNU Public License (GPLv3)
## See LICENSE for your rights.

#errorCatcher Echo

    <div id='identifier_widget' class="widget">
      <div class="widget_title">
      </div>
      <div class="widget_contents">
        <div class="footnote" style="color:red;width:100%;">
          <table style="width:95%;font-size:83px;">
            <tr>
              <td style="width:1%;"></td>
              <td id="indoor_co2" style="width:13.4%;font-family:monospace;font-style:normal;text-align:right;"></td>
              <td style="width:2%;"></td>
              <td id="indoor_aqi" style="width:10%;font-family:monospace;font-style:normal;"></td>
              <td style="width:2%;"></td>
              <td id="aqi" style="width:10%;font-family:monospace;font-style:normal;"></td>
              <td style="width:2%;"></td>
              <td id="activity-string" style="width:61.5%;font-family:monospace;font-style:normal;text-align:right;"></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
